services:
  strato_certbot:
    container_name: strato_certbot
    build:
      context: ./..
      dockerfile: docker/Dockerfile
    volumes:
      - ../config/strato-auth.json:/strato-certbot/config/strato-auth.json,ro
    #  - /my_certs:/etc/letsencrypt/live  # uncomment this to get the certificates into a volume or host
